
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saraha-backend
    ports:
      - "3000:3000"
    environment:
      -port = 3000
      -connect=mongodb://localhost:27017/saraha
      -round=4
      -key=nadakey
      -keyuser=user
      -keyadmin=admin
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./uploads:/usr/src/app/uploads

  frontend:
    image: saraha_frontend:latest
    container_name: saraha-frontend
    ports:
      - "80:80" # Assuming nginx is configured to serve on port 80
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: saraha-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
